### ISSUE TITLE
Fails to start with AttributeError: module 'quart.json' has no attribute 'JSONEncoder'

### ISSUE THREAD

**Issue by Zash** [snikket-im/snikket-web-portal#145]
**version**:   beta.20220119.2-2-gd4e8835

Built with `podman build --format docker web-portal -f web-portal/Dockerfile -t "docker.io/snikket/snikket-web-portal:zash"` and started with `podman play kube` using spec like in https://github.com/snikket-im/snikket-selfhosted/pull/8

<details><summary>AttributeError: module 'quart.json' has no attribute 'JSONEncoder'</summary>

```
Traceback (most recent call last):
  File "/usr/local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/__main__.py", line 287, in main
    run(config)
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/run.py", line 41, in run
    load_application(config.application_path, config.wsgi_max_body_size)
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/utils.py", line 115, in load_application
    module = import_module(import_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/snikket-web-portal/snikket_web/__init__.py", line 25, in <module>
    from . import colour, infra
  File "/opt/snikket-web-portal/snikket_web/infra.py", line 15, in <module>
    import flask_wtf
  File "/usr/local/lib/python3.9/dist-packages/flask_wtf/__init__.py", line 3, in <module>
    from .recaptcha import *
  File "/usr/local/lib/python3.9/dist-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/usr/local/lib/python3.9/dist-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/usr/local/lib/python3.9/dist-packages/flask_wtf/recaptcha/widgets.py", line 4, in <module>
    JSONEncoder = json.JSONEncoder
AttributeError: module 'quart.json' has no attribute 'JSONEncoder'
```

</details>

**Comment by Zash** [comment]
#141 is probably better
